# Generated by Django 3.0.3 on 2020-02-07 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0002_priority'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Priority',
        ),
        migrations.AddField(
            model_name='list',
            name='priority',
            field=models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=6),
        ),
    ]
